services:
  - type: web
    name: gbv-reporter-bot
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python gbv_report_bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        fromSecret: telegram_bot_token
      - key: AIRTABLE_API_KEY
        fromSecret: airtable_api_key
      - key: AIRTABLE_BASE_ID
        fromSecret: airtable_base_id
      - key: AIRTABLE_TABLE_NAME
        fromSecret: table_name
      - key: EMAIL_SENDER
        fromSecret: email@example.com
      - key: EMAIL_PASSWORD
        fromSecret: email_password






    
   


